name: Deploy website
on:
  pull_request:
    types:
      - closed
jobs:
  sftp-deploy:
    name: Deployment
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to ftp server
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: "public_html"
          protocol: ftps
          port: 22
          exclude: |
            LICENSE.md
            README.md
            .gitignore
            **/.idea/**
            **/.github/**
            ./assignments/**
            **/.git*/**
